server:
  port: 9191

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: employee-service-routes
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**
        - id: department-service-routes
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments/**
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG