server:
  port: 8081

spring:
  application:
    name: EMPLOYEE-SERVICE
#  config:
#    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db?useSSL=false&serverTimezone=GMT
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# actuator for CIRCUIT BREAKER
management:
  endpoint:
    health:
      enabled: true # no haría falta, ya que por defecto se muestra únicamente este endpoint
      show-details: always
  health:
    circuitbreakers:
      enabled: true


# Circuit breaker configuration
resilience4j:
  circuitbreaker:
#    configs:
#      default:
#        registerHealthIndicator: true
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        failureRateThreshold: 50 # 50%
        minimumNumberOfCalls: 5
        # CB automatically move from OPEN to HALF_OPEN after wait 5 seconds
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      EMPLOYEE-SERVICE:
        maxAttempts: 5
        waitDuration: 3s # wait duration between each retry attempt

