server:
  port: 8081

spring:
  application:
    name: EMPLOYEE-SERVICE
#  config:
#    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db?useSSL=false&serverTimezone=GMT
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/